Repository nlpsandbox/nlpsandbox-schemas, pull requests merged in 2021-01, with the labels that each got.

#140 Review PHI Deidentifier /service
  openapi/commons/paths/service.yaml
  openapi/data-node/openapi.yaml
  openapi/phi-deidentifier/openapi.yaml
Labels: Priority: Low

#138 Add health check endpoints to commons
  .gitignore
  openapi/commons/components/schemas/HealthCheck.yaml
  openapi/commons/paths/healthCheck.yaml
  openapi/data-node/openapi.yaml
Labels: Priority: Low

#146 Set TextAnnotation.text as required
  openapi/commons/components/schemas/TextAnnotation.yaml
Labels: Priority: Medium

#143 [Implement #136] Add Annotators Info Endpoint
  openapi/phi-deidentifier/components/schemas/DeidentifyResponse.yaml
  openapi/phi-deidentifier/paths/deidentifiedNotes.yaml
Labels: Priority: High
